# Generated by Django 6.0.2 on 2026-03-02 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='job_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobcompletion',
            name='job_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobassignment'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='message',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
