# Generated by Django 6.0.2 on 2026-03-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='job_attachments/'),
        ),
    ]
