# Generated by Django 6.0.2 on 2026-03-03 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcompletion',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcompletion',
            name='completion_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
