# Generated by Django 6.0.2 on 2026-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_id_alter_freelancer_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('freelancer', 'Freelancer')], default='client', max_length=20),
        ),
    ]
