# Generated by Django 6.0.3 on 2026-03-16 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='ide',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
