# Generated by Django 6.0.3 on 2026-03-16 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user'], name='reminder_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['task'], name='reminder_task_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['remind_at'], name='reminder_remind_at_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['created_at'], name='reminder_created_at_idx'),
        ),
    ]
